[project]
name = "jones-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "polars>=1.22.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
